In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [2]:
cof_data = pd.read_csv('post_dw_coffee_data.csv')

In [3]:
cof_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3547 entries, 0 to 3546
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   3547 non-null   int64
 1   hour_of_day  3547 non-null   int64
 2   cash_type    3547 non-null   object
 3   money        3547 non-null   float64
 4   coffee_name  3547 non-null   object
 5   Time_of_Day  3547 non-null   object
 6   Weekday      3547 non-null   object
 7   Month_name   3547 non-null   object
 8   Weekdaysort  3547 non-null   int64
 9   Monthsort    3547 non-null   int64
 10  Date         3547 non-null   object
 11  Time         3547 non-null   object
dtypes: float64(1), int64(4), object(7)
memory usage: 332.7+ KB

In [4]:
cof_data['Date'] = pd.to_datetime(cof_data['Date'])

In [5]:
cof_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3547 entries, 0 to 3546
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   3547 non-null   int64
 1   hour_of_day  3547 non-null   int64
 2   cash_type    3547 non-null   object
 3   money        3547 non-null   float64
 4   coffee_name  3547 non-null   object
 5   Time_of_Day  3547 non-null   object
 6   Weekday      3547 non-null   object
 7   Month_name   3547 non-null   object
 8   Weekdaysort  3547 non-null   int64
 9   Monthsort    3547 non-null   int64
 10  Date         3547 non-null   datetime64[ns]
 11  Time         3547 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(4), object(6)
memory usage: 332.7+ KB

In [6]:
cof_data.head()

,Unnamed: 0,hour_of_day,cash_type,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort,Date,Time
0,0,10,card,38.7,Latte,Morning,Fri,Mar,5,3,2024-03-01,10:15:50.520000
1,1,12,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3,2024-03-01,12:19:22.539000
2,2,12,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3,2024-03-01,12:20:18.089000
3,3,13,card,28.9,Americano,Afternoon,Fri,Mar,5,3,2024-03-01,13:46:33.006000
4,4,13,card,38.7,Latte,Afternoon,Fri,Mar,5,3,2024-03-01,13:48:14.626000

In [7]:
coffee_dat = cof_data.drop(columns=['Unnamed: 0'], inplace=False)

In [8]:
coffee_dat.isnull().sum()

hour_of_day    0
cash_type      0
money          0
coffee_name    0
Time_of_Day    0
Weekday        0
Month_name     0
Weekdaysort    0
Monthsort      0
Date           0
Time           0
dtype: int64

In [9]:
coffee_dat.describe().T

,count,mean,min,25%,50%,75%,max,std
hour_of_day,3547.0,14.185791,6.0,10.0,14.0,18.0,22.0,4.23401
money,3547.0,31.645216,18.12,27.92,32.82,35.76,38.7,4.877754
Weekdaysort,3547.0,3.845785,1.0,2.0,4.0,6.0,7.0,1.971501
Monthsort,3547.0,6.453905,1.0,3.0,7.0,10.0,12.0,3.500754
Date,3547,2024-10-04 17:34:43.676346368,2024-03-01 00:00:00,2024-07-17 12:00:00,2024-10-10 00:00:00,2025-01-11 00:00:00,2025-03-23 00:00:00,NaN

In [10]:
coffee_dat.head()

,hour_of_day,cash_type,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort,Date,Time
0,10,card,38.7,Latte,Morning,Fri,Mar,5,3,2024-03-01,10:15:50.520000
1,12,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3,2024-03-01,12:19:22.539000
2,12,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3,2024-03-01,12:20:18.089000
3,13,card,28.9,Americano,Afternoon,Fri,Mar,5,3,2024-03-01,13:46:33.006000
4,13,card,38.7,Latte,Afternoon,Fri,Mar,5,3,2024-03-01,13:48:14.626000

In [11]:
# cash_type dropped / Weekdaysort dropped (same info as Weekday) / Monthsort dropped (same info as  Month_name) / Time dropped (same info as hour_of_day
cof_data_mod = coffee_dat.drop(columns=['cash_type', 'Weekdaysort', 'Monthsort', 'Time'])

In [12]:
cof_data_mod.head()

   hour_of_day  money    coffee_name Time_of_Day Weekday Month_name       Date
0           10   38.7          Latte     Morning     Fri        Mar 2024-03-01
1           12   38.7  Hot Chocolate   Afternoon     Fri        Mar 2024-03-01
2           12   38.7  Hot Chocolate   Afternoon     Fri        Mar 2024-03-01
3           13   28.9      Americano   Afternoon     Fri        Mar 2024-03-01
4           13   38.7          Latte   Afternoon     Fri        Mar 2024-03-01

In [13]:
coff_data_encoded = pd.get_dummies(cof_data_mod, columns=['hour_of_day','coffee_name','Time_of_Day', 'Weekday', 'Month_name'], drop_first=True)

In [14]:
coff_data_encoded.columns

Index(['money', 'Date', 'hour_of_day_7', 'hour_of_day_8', 'hour_of_day_9',
       'hour_of_day_10', 'hour_of_day_11', 'hour_of_day_12', 'hour_of_day_13',
       'hour_of_day_14', 'hour_of_day_15', 'hour_of_day_16', 'hour_of_day_17',
       'hour_of_day_18', 'hour_of_day_19', 'hour_of_day_20', 'hour_of_day_21',
       'hour_of_day_22', 'coffee_name_Americano with Milk',
       'coffee_name_Cappuccino', 'coffee_name_Cocoa', 'coffee_name_Cortado',
       'coffee_name_Espresso', 'coffee_name_Hot Chocolate',
       'coffee_name_Latte', 'Time_of_Day_Morning', 'Time_of_Day_Night',
       'Weekday_Mon', 'Weekday_Sat', 'Weekday_Sun', 'Weekday_Thu',
       'Weekday_Tue', 'Weekday_Wed', 'Month_name_Aug', 'Month_name_Dec',
       'Month_name_Feb', 'Month_name_Jan', 'Month_name_Jul', 'Month_name_Jun',
       'Month_name_Mar', 'Month_name_May', 'Month_name_Nov', 'Month_name_Oct',
       'Month_name_Sep'],
      dtype='object')

In [15]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

y = coff_data_encoded['money']
date_column = coff_data_encoded['Date']
data_to_scale = coff_data_encoded.drop(columns=['money', 'Date'])

scaled_array = scaler.fit_transform(data_to_scale)

coff_data_scaled = pd.DataFrame(
    scaled_array, 
    columns=data_to_scale.columns, 
    index=data_to_scale.index
)

In [17]:
coff_data_scaled.columns

Index(['hour_of_day_7', 'hour_of_day_8', 'hour_of_day_9', 'hour_of_day_10',
       'hour_of_day_11', 'hour_of_day_12', 'hour_of_day_13', 'hour_of_day_14',
       'hour_of_day_15', 'hour_of_day_16', 'hour_of_day_17', 'hour_of_day_18',
       'hour_of_day_19', 'hour_of_day_20', 'hour_of_day_21', 'hour_of_day_22',
       'coffee_name_Americano with Milk', 'coffee_name_Cappuccino',
       'coffee_name_Cocoa', 'coffee_name_Cortado', 'coffee_name_Espresso',
       'coffee_name_Hot Chocolate', 'coffee_name_Latte', 'Time_of_Day_Morning',
       'Time_of_Day_Night', 'Weekday_Mon', 'Weekday_Sat', 'Weekday_Sun',
       'Weekday_Thu', 'Weekday_Tue', 'Weekday_Wed', 'Month_name_Aug',
       'Month_name_Dec', 'Month_name_Feb', 'Month_name_Jan', 'Month_name_Jul',
       'Month_name_Jun', 'Month_name_Mar', 'Month_name_May', 'Month_name_Nov',
       'Month_name_Oct', 'Month_name_Sep'],
      dtype='object')

In [18]:
from sklearn.model_selection import train_test_split
X = coff_data_scaled

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 123)